# Columbia University Africa Alumni Site Configuration

title: "Columbia University Africa Alumni"
short_title: "CU-AA"
email: info@cu-aa.org
description: >-
  Empowering African leaders through mentorship and community. 
  Join 90+ Columbia University alumni building Africa's future.
baseurl: ""
url: "https://cu-aa.org"
twitter_username: CU_AfricaAlumni
linkedin_url: "https://linkedin.com/company/cu-africa-alumni"

# SEO and Social
social:
  name: Columbia University Africa Alumni
  links:
    - https://twitter.com/CU_AfricaAlumni
    - https://linkedin.com/company/cu-africa-alumni

# Navigation
navigation:
  - title: Home
    url: /
  - title: About
    url: /about/
  - title: Blog
    url: /blog/
  - title: Programs
    url: /programs/
    dropdown:
      - title: Mentorship Program
        url: /programs/mentorship/
      - title: Leadership Development
        url: /programs/leadership/
  - title: Get Involved
    url: /get-involved/
  - title: Contact
    url: /contact/

# Build settings
# theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Performance
sass:
  style: compressed

# Collections
collections:
  programs:
    output: true
    permalink: /programs/:name/
  
# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "CU-AA Team"
  - scope:
      path: ""
      type: "programs"
    values:
      layout: "program"