# Columbia University Africa Alumni Site Configuration

title: "Columbia University Africa Alumni"
short_title: "CU-AA"
email: info@cu-aa.org
description: >-
  Empowering African leaders through mentorship and community. 
  Join 90+ Columbia University alumni building Africa's future.
baseurl: ""
url: "https://cu-aa.org"
twitter_username: CU_AfricaAlumni
linkedin_url: "https://linkedin.com/company/cu-africa-alumni"

# SEO and Social
social:
  name: Columbia University Africa Alumni
  links:
    - https://twitter.com/CU_AfricaAlumni
    - https://linkedin.com/company/cu-africa-alumni

# Navigation
navigation:
  - title: About
    url: /about/
  - title: Blog
    url: /blog/
  - title: Streams
    dropdown:
      - title: Community Chat
        url: /streams/community/
      - title: Economics
        url: /streams/economics/
      - title: Technology
        url: /streams/technology/
  - title: Programs
    dropdown:
      - title: Mentorship Program
        url: /programs/mentorship/
      - title: Leadership Development
        url: /programs/leadership/
      - title: Community Service
        url: /programs/community/
      - title: Events & Workshops
        url: /programs/events/
  - title: Contact
    url: /contact/

# Member area pages (these will be shown via JavaScript based on auth status)
member_pages:
  - title: Dashboard
    url: /members/dashboard/
  - title: Directory
    url: /members/directory/
  - title: Profile
    url: /members/profile/
  - title: Opportunities
    url: /members/opportunities/

# Discord Integration
discord:
  server_id: "1393296489295384726"
  invite_code: "2h2HgWFJ"
  widget_theme: "dark"

# Build settings
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Performance
sass:
  style: compressed

# Collections
collections:
  programs:
    output: true
    permalink: /programs/:name/
  
# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "CU-AA Team"
  - scope:
      path: ""
      type: "programs"
    values:
      layout: "program"

# Exclude from processing
exclude:
  - netlify-cms-oauth-provider-node/
  - node_modules/
  - vendor/
  - .bundle/
  - Gemfile
  - Gemfile.lock
  - netlify/
  - package.json
  - package-lock.json
  - .env
  - README.md